apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}--{{.Release.Name}}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}--{{.Release.Name}}
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}--{{.Release.Name}}
    namespace: {{ .Release.Namespace }}
